### ISSUE TITLE
Possible feature request to support '+' extension.

### ISSUE THREAD

**Issue by robinjohn** [Naddiseo/dart-sprintf#23]
Version used: sprintf: ^4.0.2

Can be bit more cleaner to read, if '+' is supported, with no need of '$'. 
Below is an example for a multi line string. 

Expected:
sprintf('%s', [
userAddress?.addLine1 != null ? ', ' + userAddress?.addLine1 : '' +
userAddress?.addLine2 != null ? ', ' + userAddress?.addLine2 : ''
]

Actual:
sprintf('%s', [
"${((userAddress?.addLine1) != null) ? ', ${userAddress?.addLine1}' : ''}"
"${((userAddress?.addLine2) != null) ? ', ${userAddress?.addLine2}' : ''}"
]

Thanks anyway !

**Comment by Naddiseo** [comment]
Hi @robinjohn, could you explain the issue you're having with dart-sprintf? From your examples I can't see what problem you're having with the library. If possible, could you provide an example that uses the `sprintf()` call, and I'll do my best to help?

**Comment by robinjohn** [comment]
Hey @Naddiseo , edited my first comment to include the wrapping of the two lines with sprintf.

As mentioned, this is not an issue, but only a nice-to-have-feature. 
Thanks.

**Comment by Naddiseo** [comment]
Hi @robinjohn, thanks for the edit and clarification. 

I think I see your confusion, if I understand correctly you're having issues with the operator precedence and you want the result to be: ", line1, line2".
This isn't a sprintf issue, and you'd have the same issue if you rewrite as:
```dart
var value = userAddress?.addLine1 != null ? ', ' + userAddress?.addLine1 : '' +
userAddress?.addLine2 != null ? ', ' + userAddress?.addLine2 : '';

sprintf('%s', [value]);
```
Dart is currently grouping your expression like so:
```dart
var value = userAddress?.addLine1 != null
        ? (', ' + userAddress?.addLine1)
        : ('' + userAddress?.addLine2 != null ? (', ' + userAddress?.addLine2) : '');
```

I think want you want is to group the ternary expressions together using parenthesis:
```dart
var value = (userAddress?.addLine1 != null ? ', ' + userAddress?.addLine1 : '') +
            (userAddress?.addLine2 != null ? ', ' + userAddress?.addLine2 : '');
```

I'm not even sure you need sprintf for your usecase since `sprintf("%s", [arg])` is the same as doing `arg.toString()`, and might be better written as:
```dart
var line = userAddress?.addLine1 ?? '';
if (line.isNotEmpty) {
    var add2 = userAddress?.addLine2 ?? '';
    if (add2.isNotEmpty) {
        line += ', ' + add2;
    }
}

```

**Comment by robinjohn** [comment]
Amazing clarification, thanks for the swift reply !
